version: '3.9'
services:
  mariadb:
    container_name: memberDB
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: rhleh2160
      MYSQL_DATABASE: memberDB
      MYSQL_USER: hello
      MYSQL_PASSWORD: world

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: sessionDB
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    restart: always