spring:
  datasource:
    username: root
    password: rhleh2160
    url: jdbc:mariadb://localhost:3306/memberDB

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: classpath:/application-redis.yml

  redis:
    host: localhost
    password:
    port: 6379
  session:
    store-type: redis

server:
  servlet:
    session:
      timeout: 30