spring:
  datasource:
    username: root
    password: rhleh2160
    url: jdbc:mariadb://aws-memberdb.cvlgyuiwvsz1.ap-northeast-2.rds.amazonaws.com:3306/memberDB
    driver-class-name: org.mariadb.jdbc.Driver
    name: memberDB

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: classpath:/application-redis.yml

  redis:
    host: localhost
    password:
    port: 6379
  session:
    store-type: redis

server:
  servlet:
    session:
      timeout: 30
